### ISSUE TITLE
en > nl

### ISSUE THREAD

**Issue by Maaike0904** [amirdev98/the-startup-responsive-interactieve-website#1]
<img width="129" alt="Schermafbeelding 2023-01-13 om 10 40 20" src="https://user-images.githubusercontent.com/112861144/212288194-11c71525-af80-4e07-9947-9593b4fb3f82.png">
Taal veranderen naar nl

**Comment by amirnapoletano** [comment]
https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/main/index.html#L2

ik heb de taal aangepast
