### ISSUE TITLE
styling html element 

### ISSUE THREAD

**Issue by TessaViergever** [amirdev98/the-startup-responsive-interactieve-website#10]
Hoii,

Wellicht even kijken welke styling beter past bij html of wellicht * of body

https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/52af73c45dc555c26c423506f2423d2d01b1e88e/styles.css#L5

**Comment by amirnapoletano** [comment]
https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/main/index.html#L10-L34

hier kan je zien dat ik mijn html structuur heb verbeterd.
