### ISSUE TITLE
Design: iets geks met layout

### ISSUE THREAD

**Issue by ju5tu5** [amirdev98/the-startup-responsive-interactieve-website#3]
<img width="413" alt="image" src="https://user-images.githubusercontent.com/140124/212288636-34a000cd-e223-44d3-a1a1-24be3d5f1790.png">

Werk aan je kolommen!

**Comment by amirnapoletano** [comment]
Ik heb mijn design aangepast vandaag met Sascha. De header zit er nu in en het ziet er goed uit. + hij is nu ook responsive.
