### ISSUE TITLE
Hup Hup

### ISSUE THREAD

**Issue by ju5tu5** [amirdev98/the-startup-responsive-interactieve-website#4]
https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/52af73c45dc555c26c423506f2423d2d01b1e88e/index.html#L1-L35

Je moet écht aan de slag...

**Comment by amirnapoletano** [comment]
Ik heb vandaag met behulp van Sascha mijn code verbeterd en de header er in gezet. + de website is nu responsive.
