### ISSUE TITLE
Gebruik px in layout

### ISSUE THREAD

**Issue by Stefan-Espant** [amirdev98/the-startup-responsive-interactieve-website#5]
Probeer absolute waardes als % en px te vermijden voor je layout en gebruik te maken van relatieve waardes als em, rem & vh vw.

**Comment by amirnapoletano** [comment]
px kan je vermijden maar je kan ze ook gebruiken als iets niet groter of kleiner wordt + 16 = 1rem zo zolang ik mijn root niet aanpas is het de zelfde warde. en er is niets mis met het gebruiken van %.
