### ISSUE TITLE
Typfout in CSS

### ISSUE THREAD

**Issue by DphnZwp** [amirdev98/the-startup-responsive-interactieve-website#8]
Er zit een 5 voor je footer selector.

https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/52af73c45dc555c26c423506f2423d2d01b1e88e/styles.css#L29

**Comment by amirnapoletano** [comment]
Ik heb mijn hele css opnieuw geschreven en heb deze weg gehaald
