### ISSUE TITLE
een nummer dat niet hoort op z'n plek

### ISSUE THREAD

**Issue by FouadTaissate** [amirdev98/the-startup-responsive-interactieve-website#9]
https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/52af73c45dc555c26c423506f2423d2d01b1e88e/styles.css#L29
er is de cijfer 5 hier te vinden en dat zorgt ervoor dat je nav code niet werkt

**Comment by amirnapoletano** [comment]
https://github.com/amirdev98/the-startup-responsive-interactieve-website/blob/main/index.html#L12

deze heb ik weg gehaald.
